Algoritmo "ImprimeRepitaAte10a1"
//
//
//
//
// Descrição do curso   : estrutura de Repetição - Repita-ate(do-while)
// Autor(a)    : Ronildo Fonseca
// Data atual  : 29/10/2022
Var
   // Variávelj
   j:inteiro

Inicio
   //A repetição acontecerá até chegar o número 1
   escreval("Imprimindo de 10 a 1 Repita ate:")
   escreval()
   j<-10
   repita
      escreval(j)
      j<-j-1
   ate j< 1
   escreval()
   escreval("O valor de J = ",j)

Fimalgoritmo