Algoritmo "ImprimeRepitaAte1a10"
//
//
//
//
// Descrição do curso   : estrutura de Repetição - Repita-ate(do-while)
// Autor(a)    : Ronildo Fonseca
// Data atual  : 29/10/2022
Var
   // Variávelj
   j:inteiro

Inicio
   //A repetição acontecerá até chegar o número 1
   escreval("Imprimindo de 1 a 10 Repita ate:")
   escreval()
   j<- 1
   repita
      escreval(j)
      j<-j+1
   ate j> 10
   escreval()
   escreval("O valor de J = ",j)

Fimalgoritmo