Algoritmo "SomaNumerosInteiros"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/10/2022
Var
// Variáveis
soma, i: inteiro


Inicio
//Soma e repete até 100
 soma <-0
 i<-1
 
 repita
 soma<-soma+i
 i<-i+1
 ate i > 100
 escreval()
 escreval("A soma dos numeros inteiros até 100 é",soma)

Fimalgoritmo